import { Button } from "antd";
import Head from "next/head";
import { useContext } from "react";
import { AuthContext } from "../src/context/auth";

export default function Home() {
  //context
  const [auth, setAuth] = useContext(AuthContext);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
      <Button type="primary">Primary Button</Button>
      <pre>{JSON.stringify(auth, null, 4)}</pre>
    </div>
  );
}
